package tom2oracle.data;
// Generated Sep 18, 2015 9:55:49 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Fusion generated by hbm2java
 */
@Entity
@Table(name="FUSION"
    ,schema="TOM_20150918"
)
public class Fusion  implements java.io.Serializable {


     private BigDecimal fusionSaid;
     private String libraryPrep;
     private String sampleName;
     private String pipeline;
     private String fusionGene1;
     private String fusionGene2;
     private BigDecimal junctionReads;
     private BigDecimal spanningFrags;

    public Fusion() {
    }

	
    public Fusion(BigDecimal fusionSaid, String libraryPrep, String sampleName, String pipeline) {
        this.fusionSaid = fusionSaid;
        this.libraryPrep = libraryPrep;
        this.sampleName = sampleName;
        this.pipeline = pipeline;
    }
    public Fusion(BigDecimal fusionSaid, String libraryPrep, String sampleName, String pipeline, String fusionGene1, String fusionGene2, BigDecimal junctionReads, BigDecimal spanningFrags) {
       this.fusionSaid = fusionSaid;
       this.libraryPrep = libraryPrep;
       this.sampleName = sampleName;
       this.pipeline = pipeline;
       this.fusionGene1 = fusionGene1;
       this.fusionGene2 = fusionGene2;
       this.junctionReads = junctionReads;
       this.spanningFrags = spanningFrags;
    }
   
     @Id 

    
    @Column(name="FUSION_SAID", unique=true, nullable=false, precision=22, scale=0)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "G1")
@SequenceGenerator(name = "G1", sequenceName = "SAID_SEQ")    
    public BigDecimal getFusionSaid() {
        return this.fusionSaid;
    }
    
    public void setFusionSaid(BigDecimal fusionSaid) {
        this.fusionSaid = fusionSaid;
    }

    
    @Column(name="LIBRARY_PREP", nullable=false, length=100)
    public String getLibraryPrep() {
        return this.libraryPrep;
    }
    
    public void setLibraryPrep(String libraryPrep) {
        this.libraryPrep = libraryPrep;
    }

    
    @Column(name="SAMPLE_NAME", nullable=false, length=100)
    public String getSampleName() {
        return this.sampleName;
    }
    
    public void setSampleName(String sampleName) {
        this.sampleName = sampleName;
    }

    
    @Column(name="PIPELINE", nullable=false, length=100)
    public String getPipeline() {
        return this.pipeline;
    }
    
    public void setPipeline(String pipeline) {
        this.pipeline = pipeline;
    }

    
    @Column(name="FUSION_GENE1", length=2000)
    public String getFusionGene1() {
        return this.fusionGene1;
    }
    
    public void setFusionGene1(String fusionGene1) {
        this.fusionGene1 = fusionGene1;
    }

    
    @Column(name="FUSION_GENE2", length=2000)
    public String getFusionGene2() {
        return this.fusionGene2;
    }
    
    public void setFusionGene2(String fusionGene2) {
        this.fusionGene2 = fusionGene2;
    }

    
    @Column(name="JUNCTION_READS", precision=22, scale=0)
    public BigDecimal getJunctionReads() {
        return this.junctionReads;
    }
    
    public void setJunctionReads(BigDecimal junctionReads) {
        this.junctionReads = junctionReads;
    }

    
    @Column(name="SPANNING_FRAGS", precision=22, scale=0)
    public BigDecimal getSpanningFrags() {
        return this.spanningFrags;
    }
    
    public void setSpanningFrags(BigDecimal spanningFrags) {
        this.spanningFrags = spanningFrags;
    }




}


