package tom2oracle.data;
// Generated Feb 29, 2016 4:20:17 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Mafannovar generated by hbm2java
 */
@Entity
@Table(name="MAFANNOVAR"
    ,schema="TOM_20160225"
)
public class Mafannovar  implements java.io.Serializable {


     private BigDecimal mafannovarSaid;
     private String libraryPrep;
     private String sampleName;
     private String pipeline;
     private String tumorSampleBarcode;
     private String hugoSymbol;
     private String variantClassification;
     private String consequence;
     private String geneRefgene;
     private String funcRefgene;
     private String exonicFuncRefgene;
     private String aachangeRefgene;
     private String chromosome;
     private BigDecimal startPosition;
     private BigDecimal endPosition;
     private String chromosomevep;
     private BigDecimal startvep;
     private BigDecimal endvep;
     private String biotype;
     private String dbsnpRs;
     private String one000g2014sepAll;
     private String snp138;
     private String hgvsc;
     private String hgvsp;
     private String transcript;
     private String exonNumber;
     private String refseq;
     private String existingVariation;
     private String domains;
     private String pubmed;
     private String refBase;
     private String altBase;
     private String cosmic70;
     private BigDecimal cosmic70TotalOccurrences;
     private BigDecimal exacAll;
     private BigDecimal exacAfr;
     private BigDecimal exacAmr;
     private BigDecimal exacEas;
     private BigDecimal exacFin;
     private BigDecimal exacNfe;
     private BigDecimal exacOth;
     private BigDecimal exacSas;
     private BigDecimal altVariantFreq;
     private BigDecimal readDepth;
     private BigDecimal altReadDepth;
     private String clinvar20140929;
     private BigDecimal siftScore;
     private String siftPred;
     private BigDecimal polyphen2HdivScore;
     private String polyphen2HdivPred;
     private String polyphen2HvarPred;
     private String lrtPred;
     private String mutationtasterPred;
     private String mutationassessorPred;
     private String fathmmklCodingPred;
     private BigDecimal metasvmScore;
     private String metasvmPred;
     private String fathmmPred;
     private String proveanPred;
     private String metalrPred;
     private BigDecimal polyphen2HvarScore;
     private BigDecimal lrtScore;
     private BigDecimal mutationtasterScore;
     private BigDecimal mutationassessorScore;
     private BigDecimal fathmmScore;
     private BigDecimal proveanScore;
     private BigDecimal vest3Score;
     private BigDecimal caddRaw;
     private BigDecimal caddPhred;
     private BigDecimal dannScore;
     private BigDecimal fathmmmklCodingScore;
     private BigDecimal metalrScore;
     private BigDecimal integratedFitconsScore;
     private BigDecimal gerpRs;
     private BigDecimal phylop7wayVertebrate;
     private BigDecimal phylop20wayMammalian;
     private BigDecimal phastcons7wayVertebrate;
     private BigDecimal phastcons20wayMammalian;
     private BigDecimal siphy29wayLogodds;
     private String interproDomain;

    public Mafannovar() {
    }

	
    public Mafannovar(BigDecimal mafannovarSaid, String libraryPrep, String sampleName, String pipeline) {
        this.mafannovarSaid = mafannovarSaid;
        this.libraryPrep = libraryPrep;
        this.sampleName = sampleName;
        this.pipeline = pipeline;
    }
    public Mafannovar(BigDecimal mafannovarSaid, String libraryPrep, String sampleName, String pipeline, String tumorSampleBarcode, String hugoSymbol, String variantClassification, String consequence, String geneRefgene, String funcRefgene, String exonicFuncRefgene, String aachangeRefgene, String chromosome, BigDecimal startPosition, BigDecimal endPosition, String chromosomevep, BigDecimal startvep, BigDecimal endvep, String biotype, String dbsnpRs, String one000g2014sepAll, String snp138, String hgvsc, String hgvsp, String transcript, String exonNumber, String refseq, String existingVariation, String domains, String pubmed, String refBase, String altBase, String cosmic70, BigDecimal cosmic70TotalOccurrences, BigDecimal exacAll, BigDecimal exacAfr, BigDecimal exacAmr, BigDecimal exacEas, BigDecimal exacFin, BigDecimal exacNfe, BigDecimal exacOth, BigDecimal exacSas, BigDecimal altVariantFreq, BigDecimal readDepth, BigDecimal altReadDepth, String clinvar20140929, BigDecimal siftScore, String siftPred, BigDecimal polyphen2HdivScore, String polyphen2HdivPred, String polyphen2HvarPred, String lrtPred, String mutationtasterPred, String mutationassessorPred, String fathmmklCodingPred, BigDecimal metasvmScore, String metasvmPred, String fathmmPred, String proveanPred, String metalrPred, BigDecimal polyphen2HvarScore, BigDecimal lrtScore, BigDecimal mutationtasterScore, BigDecimal mutationassessorScore, BigDecimal fathmmScore, BigDecimal proveanScore, BigDecimal vest3Score, BigDecimal caddRaw, BigDecimal caddPhred, BigDecimal dannScore, BigDecimal fathmmmklCodingScore, BigDecimal metalrScore, BigDecimal integratedFitconsScore, BigDecimal gerpRs, BigDecimal phylop7wayVertebrate, BigDecimal phylop20wayMammalian, BigDecimal phastcons7wayVertebrate, BigDecimal phastcons20wayMammalian, BigDecimal siphy29wayLogodds, String interproDomain) {
       this.mafannovarSaid = mafannovarSaid;
       this.libraryPrep = libraryPrep;
       this.sampleName = sampleName;
       this.pipeline = pipeline;
       this.tumorSampleBarcode = tumorSampleBarcode;
       this.hugoSymbol = hugoSymbol;
       this.variantClassification = variantClassification;
       this.consequence = consequence;
       this.geneRefgene = geneRefgene;
       this.funcRefgene = funcRefgene;
       this.exonicFuncRefgene = exonicFuncRefgene;
       this.aachangeRefgene = aachangeRefgene;
       this.chromosome = chromosome;
       this.startPosition = startPosition;
       this.endPosition = endPosition;
       this.chromosomevep = chromosomevep;
       this.startvep = startvep;
       this.endvep = endvep;
       this.biotype = biotype;
       this.dbsnpRs = dbsnpRs;
       this.one000g2014sepAll = one000g2014sepAll;
       this.snp138 = snp138;
       this.hgvsc = hgvsc;
       this.hgvsp = hgvsp;
       this.transcript = transcript;
       this.exonNumber = exonNumber;
       this.refseq = refseq;
       this.existingVariation = existingVariation;
       this.domains = domains;
       this.pubmed = pubmed;
       this.refBase = refBase;
       this.altBase = altBase;
       this.cosmic70 = cosmic70;
       this.cosmic70TotalOccurrences = cosmic70TotalOccurrences;
       this.exacAll = exacAll;
       this.exacAfr = exacAfr;
       this.exacAmr = exacAmr;
       this.exacEas = exacEas;
       this.exacFin = exacFin;
       this.exacNfe = exacNfe;
       this.exacOth = exacOth;
       this.exacSas = exacSas;
       this.altVariantFreq = altVariantFreq;
       this.readDepth = readDepth;
       this.altReadDepth = altReadDepth;
       this.clinvar20140929 = clinvar20140929;
       this.siftScore = siftScore;
       this.siftPred = siftPred;
       this.polyphen2HdivScore = polyphen2HdivScore;
       this.polyphen2HdivPred = polyphen2HdivPred;
       this.polyphen2HvarPred = polyphen2HvarPred;
       this.lrtPred = lrtPred;
       this.mutationtasterPred = mutationtasterPred;
       this.mutationassessorPred = mutationassessorPred;
       this.fathmmklCodingPred = fathmmklCodingPred;
       this.metasvmScore = metasvmScore;
       this.metasvmPred = metasvmPred;
       this.fathmmPred = fathmmPred;
       this.proveanPred = proveanPred;
       this.metalrPred = metalrPred;
       this.polyphen2HvarScore = polyphen2HvarScore;
       this.lrtScore = lrtScore;
       this.mutationtasterScore = mutationtasterScore;
       this.mutationassessorScore = mutationassessorScore;
       this.fathmmScore = fathmmScore;
       this.proveanScore = proveanScore;
       this.vest3Score = vest3Score;
       this.caddRaw = caddRaw;
       this.caddPhred = caddPhred;
       this.dannScore = dannScore;
       this.fathmmmklCodingScore = fathmmmklCodingScore;
       this.metalrScore = metalrScore;
       this.integratedFitconsScore = integratedFitconsScore;
       this.gerpRs = gerpRs;
       this.phylop7wayVertebrate = phylop7wayVertebrate;
       this.phylop20wayMammalian = phylop20wayMammalian;
       this.phastcons7wayVertebrate = phastcons7wayVertebrate;
       this.phastcons20wayMammalian = phastcons20wayMammalian;
       this.siphy29wayLogodds = siphy29wayLogodds;
       this.interproDomain = interproDomain;
    }
   
     @Id 

    
    @Column(name="MAFANNOVAR_SAID", unique=true, nullable=false, precision=22, scale=0)
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "G1")
    @SequenceGenerator(name = "G1", sequenceName = "SAID_SEQ")
    public BigDecimal getMafannovarSaid() {
        return this.mafannovarSaid;
    }
    
    public void setMafannovarSaid(BigDecimal mafannovarSaid) {
        this.mafannovarSaid = mafannovarSaid;
    }

    
    @Column(name="LIBRARY_PREP", nullable=false, length=100)
    public String getLibraryPrep() {
        return this.libraryPrep;
    }
    
    public void setLibraryPrep(String libraryPrep) {
        this.libraryPrep = libraryPrep;
    }

    
    @Column(name="SAMPLE_NAME", nullable=false, length=100)
    public String getSampleName() {
        return this.sampleName;
    }
    
    public void setSampleName(String sampleName) {
        this.sampleName = sampleName;
    }

    
    @Column(name="PIPELINE", nullable=false, length=100)
    public String getPipeline() {
        return this.pipeline;
    }
    
    public void setPipeline(String pipeline) {
        this.pipeline = pipeline;
    }

    
    @Column(name="TUMOR_SAMPLE_BARCODE", length=2000)
    public String getTumorSampleBarcode() {
        return this.tumorSampleBarcode;
    }
    
    public void setTumorSampleBarcode(String tumorSampleBarcode) {
        this.tumorSampleBarcode = tumorSampleBarcode;
    }

    
    @Column(name="HUGO_SYMBOL", length=2000)
    public String getHugoSymbol() {
        return this.hugoSymbol;
    }
    
    public void setHugoSymbol(String hugoSymbol) {
        this.hugoSymbol = hugoSymbol;
    }

    
    @Column(name="VARIANT_CLASSIFICATION", length=2000)
    public String getVariantClassification() {
        return this.variantClassification;
    }
    
    public void setVariantClassification(String variantClassification) {
        this.variantClassification = variantClassification;
    }

    
    @Column(name="CONSEQUENCE", length=2000)
    public String getConsequence() {
        return this.consequence;
    }
    
    public void setConsequence(String consequence) {
        this.consequence = consequence;
    }

    
    @Column(name="GENE_REFGENE", length=1000)
    public String getGeneRefgene() {
        return this.geneRefgene;
    }
    
    public void setGeneRefgene(String geneRefgene) {
        this.geneRefgene = geneRefgene;
    }

    
    @Column(name="FUNC_REFGENE", length=1000)
    public String getFuncRefgene() {
        return this.funcRefgene;
    }
    
    public void setFuncRefgene(String funcRefgene) {
        this.funcRefgene = funcRefgene;
    }

    
    @Column(name="EXONIC_FUNC_REFGENE", length=2000)
    public String getExonicFuncRefgene() {
        return this.exonicFuncRefgene;
    }
    
    public void setExonicFuncRefgene(String exonicFuncRefgene) {
        this.exonicFuncRefgene = exonicFuncRefgene;
    }

    
    @Column(name="AACHANGE_REFGENE", length=2000)
    public String getAachangeRefgene() {
        return this.aachangeRefgene;
    }
    
    public void setAachangeRefgene(String aachangeRefgene) {
        this.aachangeRefgene = aachangeRefgene;
    }

    
    @Column(name="CHROMOSOME", length=2000)
    public String getChromosome() {
        return this.chromosome;
    }
    
    public void setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }

    
    @Column(name="START_POSITION", precision=22, scale=0)
    public BigDecimal getStartPosition() {
        return this.startPosition;
    }
    
    public void setStartPosition(BigDecimal startPosition) {
        this.startPosition = startPosition;
    }

    
    @Column(name="END_POSITION", precision=22, scale=0)
    public BigDecimal getEndPosition() {
        return this.endPosition;
    }
    
    public void setEndPosition(BigDecimal endPosition) {
        this.endPosition = endPosition;
    }

    
    @Column(name="CHROMOSOMEVEP", length=2000)
    public String getChromosomevep() {
        return this.chromosomevep;
    }
    
    public void setChromosomevep(String chromosomevep) {
        this.chromosomevep = chromosomevep;
    }

    
    @Column(name="STARTVEP", precision=22, scale=0)
    public BigDecimal getStartvep() {
        return this.startvep;
    }
    
    public void setStartvep(BigDecimal startvep) {
        this.startvep = startvep;
    }

    
    @Column(name="ENDVEP", precision=22, scale=0)
    public BigDecimal getEndvep() {
        return this.endvep;
    }
    
    public void setEndvep(BigDecimal endvep) {
        this.endvep = endvep;
    }

    
    @Column(name="BIOTYPE", length=2000)
    public String getBiotype() {
        return this.biotype;
    }
    
    public void setBiotype(String biotype) {
        this.biotype = biotype;
    }

    
    @Column(name="DBSNP_RS", length=2000)
    public String getDbsnpRs() {
        return this.dbsnpRs;
    }
    
    public void setDbsnpRs(String dbsnpRs) {
        this.dbsnpRs = dbsnpRs;
    }

    
    @Column(name="ONE000G2014SEP_ALL", length=2000)
    public String getOne000g2014sepAll() {
        return this.one000g2014sepAll;
    }
    
    public void setOne000g2014sepAll(String one000g2014sepAll) {
        this.one000g2014sepAll = one000g2014sepAll;
    }

    
    @Column(name="SNP138", length=2000)
    public String getSnp138() {
        return this.snp138;
    }
    
    public void setSnp138(String snp138) {
        this.snp138 = snp138;
    }

    
    @Column(name="HGVSC", length=2000)
    public String getHgvsc() {
        return this.hgvsc;
    }
    
    public void setHgvsc(String hgvsc) {
        this.hgvsc = hgvsc;
    }

    
    @Column(name="HGVSP", length=2000)
    public String getHgvsp() {
        return this.hgvsp;
    }
    
    public void setHgvsp(String hgvsp) {
        this.hgvsp = hgvsp;
    }

    
    @Column(name="TRANSCRIPT", length=2000)
    public String getTranscript() {
        return this.transcript;
    }
    
    public void setTranscript(String transcript) {
        this.transcript = transcript;
    }

    
    @Column(name="EXON_NUMBER", length=2000)
    public String getExonNumber() {
        return this.exonNumber;
    }
    
    public void setExonNumber(String exonNumber) {
        this.exonNumber = exonNumber;
    }

    
    @Column(name="REFSEQ", length=2000)
    public String getRefseq() {
        return this.refseq;
    }
    
    public void setRefseq(String refseq) {
        this.refseq = refseq;
    }

    
    @Column(name="EXISTING_VARIATION", length=2000)
    public String getExistingVariation() {
        return this.existingVariation;
    }
    
    public void setExistingVariation(String existingVariation) {
        this.existingVariation = existingVariation;
    }

    
    @Column(name="DOMAINS", length=2000)
    public String getDomains() {
        return this.domains;
    }
    
    public void setDomains(String domains) {
        this.domains = domains;
    }

    
    @Column(name="PUBMED", length=2000)
    public String getPubmed() {
        return this.pubmed;
    }
    
    public void setPubmed(String pubmed) {
        this.pubmed = pubmed;
    }

    
    @Column(name="REF_BASE", length=2000)
    public String getRefBase() {
        return this.refBase;
    }
    
    public void setRefBase(String refBase) {
        this.refBase = refBase;
    }

    
    @Column(name="ALT_BASE", length=2000)
    public String getAltBase() {
        return this.altBase;
    }
    
    public void setAltBase(String altBase) {
        this.altBase = altBase;
    }

    
    @Column(name="COSMIC70", length=2000)
    public String getCosmic70() {
        return this.cosmic70;
    }
    
    public void setCosmic70(String cosmic70) {
        this.cosmic70 = cosmic70;
    }

    
    @Column(name="COSMIC70_TOTAL_OCCURRENCES", precision=22, scale=0)
    public BigDecimal getCosmic70TotalOccurrences() {
        return this.cosmic70TotalOccurrences;
    }
    
    public void setCosmic70TotalOccurrences(BigDecimal cosmic70TotalOccurrences) {
        this.cosmic70TotalOccurrences = cosmic70TotalOccurrences;
    }

    
    @Column(name="EXAC_ALL", precision=22, scale=0)
    public BigDecimal getExacAll() {
        return this.exacAll;
    }
    
    public void setExacAll(BigDecimal exacAll) {
        this.exacAll = exacAll;
    }

    
    @Column(name="EXAC_AFR", precision=22, scale=0)
    public BigDecimal getExacAfr() {
        return this.exacAfr;
    }
    
    public void setExacAfr(BigDecimal exacAfr) {
        this.exacAfr = exacAfr;
    }

    
    @Column(name="EXAC_AMR", precision=22, scale=0)
    public BigDecimal getExacAmr() {
        return this.exacAmr;
    }
    
    public void setExacAmr(BigDecimal exacAmr) {
        this.exacAmr = exacAmr;
    }

    
    @Column(name="EXAC_EAS", precision=22, scale=0)
    public BigDecimal getExacEas() {
        return this.exacEas;
    }
    
    public void setExacEas(BigDecimal exacEas) {
        this.exacEas = exacEas;
    }

    
    @Column(name="EXAC_FIN", precision=22, scale=0)
    public BigDecimal getExacFin() {
        return this.exacFin;
    }
    
    public void setExacFin(BigDecimal exacFin) {
        this.exacFin = exacFin;
    }

    
    @Column(name="EXAC_NFE", precision=22, scale=0)
    public BigDecimal getExacNfe() {
        return this.exacNfe;
    }
    
    public void setExacNfe(BigDecimal exacNfe) {
        this.exacNfe = exacNfe;
    }

    
    @Column(name="EXAC_OTH", precision=22, scale=0)
    public BigDecimal getExacOth() {
        return this.exacOth;
    }
    
    public void setExacOth(BigDecimal exacOth) {
        this.exacOth = exacOth;
    }

    
    @Column(name="EXAC_SAS", precision=22, scale=0)
    public BigDecimal getExacSas() {
        return this.exacSas;
    }
    
    public void setExacSas(BigDecimal exacSas) {
        this.exacSas = exacSas;
    }

    
    @Column(name="ALT_VARIANT_FREQ", precision=22, scale=0)
    public BigDecimal getAltVariantFreq() {
        return this.altVariantFreq;
    }
    
    public void setAltVariantFreq(BigDecimal altVariantFreq) {
        this.altVariantFreq = altVariantFreq;
    }

    
    @Column(name="READ_DEPTH", precision=22, scale=0)
    public BigDecimal getReadDepth() {
        return this.readDepth;
    }
    
    public void setReadDepth(BigDecimal readDepth) {
        this.readDepth = readDepth;
    }

    
    @Column(name="ALT_READ_DEPTH", precision=22, scale=0)
    public BigDecimal getAltReadDepth() {
        return this.altReadDepth;
    }
    
    public void setAltReadDepth(BigDecimal altReadDepth) {
        this.altReadDepth = altReadDepth;
    }

    
    @Column(name="CLINVAR_20140929", length=2000)
    public String getClinvar20140929() {
        return this.clinvar20140929;
    }
    
    public void setClinvar20140929(String clinvar20140929) {
        this.clinvar20140929 = clinvar20140929;
    }

    
    @Column(name="SIFT_SCORE", precision=22, scale=0)
    public BigDecimal getSiftScore() {
        return this.siftScore;
    }
    
    public void setSiftScore(BigDecimal siftScore) {
        this.siftScore = siftScore;
    }

    
    @Column(name="SIFT_PRED", length=2000)
    public String getSiftPred() {
        return this.siftPred;
    }
    
    public void setSiftPred(String siftPred) {
        this.siftPred = siftPred;
    }

    
    @Column(name="POLYPHEN2_HDIV_SCORE", precision=22, scale=0)
    public BigDecimal getPolyphen2HdivScore() {
        return this.polyphen2HdivScore;
    }
    
    public void setPolyphen2HdivScore(BigDecimal polyphen2HdivScore) {
        this.polyphen2HdivScore = polyphen2HdivScore;
    }

    
    @Column(name="POLYPHEN2_HDIV_PRED", length=2000)
    public String getPolyphen2HdivPred() {
        return this.polyphen2HdivPred;
    }
    
    public void setPolyphen2HdivPred(String polyphen2HdivPred) {
        this.polyphen2HdivPred = polyphen2HdivPred;
    }

    
    @Column(name="POLYPHEN2_HVAR_PRED", length=2000)
    public String getPolyphen2HvarPred() {
        return this.polyphen2HvarPred;
    }
    
    public void setPolyphen2HvarPred(String polyphen2HvarPred) {
        this.polyphen2HvarPred = polyphen2HvarPred;
    }

    
    @Column(name="LRT_PRED", length=2000)
    public String getLrtPred() {
        return this.lrtPred;
    }
    
    public void setLrtPred(String lrtPred) {
        this.lrtPred = lrtPred;
    }

    
    @Column(name="MUTATIONTASTER_PRED", length=2000)
    public String getMutationtasterPred() {
        return this.mutationtasterPred;
    }
    
    public void setMutationtasterPred(String mutationtasterPred) {
        this.mutationtasterPred = mutationtasterPred;
    }

    
    @Column(name="MUTATIONASSESSOR_PRED", length=2000)
    public String getMutationassessorPred() {
        return this.mutationassessorPred;
    }
    
    public void setMutationassessorPred(String mutationassessorPred) {
        this.mutationassessorPred = mutationassessorPred;
    }

    
    @Column(name="FATHMMKL_CODING_PRED", length=2000)
    public String getFathmmklCodingPred() {
        return this.fathmmklCodingPred;
    }
    
    public void setFathmmklCodingPred(String fathmmklCodingPred) {
        this.fathmmklCodingPred = fathmmklCodingPred;
    }

    
    @Column(name="METASVM_SCORE", precision=22, scale=0)
    public BigDecimal getMetasvmScore() {
        return this.metasvmScore;
    }
    
    public void setMetasvmScore(BigDecimal metasvmScore) {
        this.metasvmScore = metasvmScore;
    }

    
    @Column(name="METASVM_PRED", length=2000)
    public String getMetasvmPred() {
        return this.metasvmPred;
    }
    
    public void setMetasvmPred(String metasvmPred) {
        this.metasvmPred = metasvmPred;
    }

    
    @Column(name="FATHMM_PRED", length=2000)
    public String getFathmmPred() {
        return this.fathmmPred;
    }
    
    public void setFathmmPred(String fathmmPred) {
        this.fathmmPred = fathmmPred;
    }

    
    @Column(name="PROVEAN_PRED", length=2000)
    public String getProveanPred() {
        return this.proveanPred;
    }
    
    public void setProveanPred(String proveanPred) {
        this.proveanPred = proveanPred;
    }

    
    @Column(name="METALR_PRED", length=2000)
    public String getMetalrPred() {
        return this.metalrPred;
    }
    
    public void setMetalrPred(String metalrPred) {
        this.metalrPred = metalrPred;
    }

    
    @Column(name="POLYPHEN2_HVAR_SCORE", precision=22, scale=0)
    public BigDecimal getPolyphen2HvarScore() {
        return this.polyphen2HvarScore;
    }
    
    public void setPolyphen2HvarScore(BigDecimal polyphen2HvarScore) {
        this.polyphen2HvarScore = polyphen2HvarScore;
    }

    
    @Column(name="LRT_SCORE", precision=22, scale=0)
    public BigDecimal getLrtScore() {
        return this.lrtScore;
    }
    
    public void setLrtScore(BigDecimal lrtScore) {
        this.lrtScore = lrtScore;
    }

    
    @Column(name="MUTATIONTASTER_SCORE", precision=22, scale=0)
    public BigDecimal getMutationtasterScore() {
        return this.mutationtasterScore;
    }
    
    public void setMutationtasterScore(BigDecimal mutationtasterScore) {
        this.mutationtasterScore = mutationtasterScore;
    }

    
    @Column(name="MUTATIONASSESSOR_SCORE", precision=22, scale=0)
    public BigDecimal getMutationassessorScore() {
        return this.mutationassessorScore;
    }
    
    public void setMutationassessorScore(BigDecimal mutationassessorScore) {
        this.mutationassessorScore = mutationassessorScore;
    }

    
    @Column(name="FATHMM_SCORE", precision=22, scale=0)
    public BigDecimal getFathmmScore() {
        return this.fathmmScore;
    }
    
    public void setFathmmScore(BigDecimal fathmmScore) {
        this.fathmmScore = fathmmScore;
    }

    
    @Column(name="PROVEAN_SCORE", precision=22, scale=0)
    public BigDecimal getProveanScore() {
        return this.proveanScore;
    }
    
    public void setProveanScore(BigDecimal proveanScore) {
        this.proveanScore = proveanScore;
    }

    
    @Column(name="VEST3_SCORE", precision=22, scale=0)
    public BigDecimal getVest3Score() {
        return this.vest3Score;
    }
    
    public void setVest3Score(BigDecimal vest3Score) {
        this.vest3Score = vest3Score;
    }

    
    @Column(name="CADD_RAW", precision=22, scale=0)
    public BigDecimal getCaddRaw() {
        return this.caddRaw;
    }
    
    public void setCaddRaw(BigDecimal caddRaw) {
        this.caddRaw = caddRaw;
    }

    
    @Column(name="CADD_PHRED", precision=22, scale=0)
    public BigDecimal getCaddPhred() {
        return this.caddPhred;
    }
    
    public void setCaddPhred(BigDecimal caddPhred) {
        this.caddPhred = caddPhred;
    }

    
    @Column(name="DANN_SCORE", precision=22, scale=0)
    public BigDecimal getDannScore() {
        return this.dannScore;
    }
    
    public void setDannScore(BigDecimal dannScore) {
        this.dannScore = dannScore;
    }

    
    @Column(name="FATHMMMKL_CODING_SCORE", precision=22, scale=0)
    public BigDecimal getFathmmmklCodingScore() {
        return this.fathmmmklCodingScore;
    }
    
    public void setFathmmmklCodingScore(BigDecimal fathmmmklCodingScore) {
        this.fathmmmklCodingScore = fathmmmklCodingScore;
    }

    
    @Column(name="METALR_SCORE", precision=22, scale=0)
    public BigDecimal getMetalrScore() {
        return this.metalrScore;
    }
    
    public void setMetalrScore(BigDecimal metalrScore) {
        this.metalrScore = metalrScore;
    }

    
    @Column(name="INTEGRATED_FITCONS_SCORE", precision=22, scale=0)
    public BigDecimal getIntegratedFitconsScore() {
        return this.integratedFitconsScore;
    }
    
    public void setIntegratedFitconsScore(BigDecimal integratedFitconsScore) {
        this.integratedFitconsScore = integratedFitconsScore;
    }

    
    @Column(name="GERP_RS", precision=22, scale=0)
    public BigDecimal getGerpRs() {
        return this.gerpRs;
    }
    
    public void setGerpRs(BigDecimal gerpRs) {
        this.gerpRs = gerpRs;
    }

    
    @Column(name="PHYLOP7WAY_VERTEBRATE", precision=22, scale=0)
    public BigDecimal getPhylop7wayVertebrate() {
        return this.phylop7wayVertebrate;
    }
    
    public void setPhylop7wayVertebrate(BigDecimal phylop7wayVertebrate) {
        this.phylop7wayVertebrate = phylop7wayVertebrate;
    }

    
    @Column(name="PHYLOP20WAY_MAMMALIAN", precision=22, scale=0)
    public BigDecimal getPhylop20wayMammalian() {
        return this.phylop20wayMammalian;
    }
    
    public void setPhylop20wayMammalian(BigDecimal phylop20wayMammalian) {
        this.phylop20wayMammalian = phylop20wayMammalian;
    }

    
    @Column(name="PHASTCONS7WAY_VERTEBRATE", precision=22, scale=0)
    public BigDecimal getPhastcons7wayVertebrate() {
        return this.phastcons7wayVertebrate;
    }
    
    public void setPhastcons7wayVertebrate(BigDecimal phastcons7wayVertebrate) {
        this.phastcons7wayVertebrate = phastcons7wayVertebrate;
    }

    
    @Column(name="PHASTCONS20WAY_MAMMALIAN", precision=22, scale=0)
    public BigDecimal getPhastcons20wayMammalian() {
        return this.phastcons20wayMammalian;
    }
    
    public void setPhastcons20wayMammalian(BigDecimal phastcons20wayMammalian) {
        this.phastcons20wayMammalian = phastcons20wayMammalian;
    }

    
    @Column(name="SIPHY_29WAY_LOGODDS", precision=22, scale=0)
    public BigDecimal getSiphy29wayLogodds() {
        return this.siphy29wayLogodds;
    }
    
    public void setSiphy29wayLogodds(BigDecimal siphy29wayLogodds) {
        this.siphy29wayLogodds = siphy29wayLogodds;
    }

    
    @Column(name="INTERPRO_DOMAIN", length=2000)
    public String getInterproDomain() {
        return this.interproDomain;
    }
    
    public void setInterproDomain(String interproDomain) {
        this.interproDomain = interproDomain;
    }




}


